version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'PBRP or other manifest branch'
      # PBRP_BRANCH: '' # optional, if not default 'android-9.0', define other bootable_recovery branch
      VERSION: '2.9.1' # as of now, the current PBRP version
      MAINTAINER: '@########'
      VENDOR: 'Product Vendor or Manufacturer'
      CODENAME: 'Device Codename'
      BUILD_LUNCH: '' # set like 'omni_$CODENAME-userdebug' or 'omni_$CODENAME-eng'
      TEST_BUILD: '' # set 'true' for testing, otherwise do not use at all (for official)
      # PB_OFFICIAL: 'true' # Set true only for Stable Official builds
      EXTRA_CMD: # some required commands like `ls` after `repo sync`, write in single line
      # PB_ENGLISH: 'true' # If you want only English Language
      CHANGELOG: " - Update 1\n
        - Update or Fix 2\n
        - Update or Fix 3\n
        - ........\n
        - Upto N"

    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global credential.helper store
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'REPLACE CURRENT BRANCH NAME HERE'
          context: org-global
